config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root :to => "homes#top"
    get '/about' => "homes#about"
    resources :items, only: [:index, :show]

    devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
    }

    resource :customers, only: [:show] do
      collection do
        get 'information/edit' => 'customers#edit'
        patch 'information' => 'customers#update'
        get 'check'
        patch 'leave'
      end
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get 'confirm'
        get 'complete'
      end
    end
    resources :addresses, except: [:new, :show]
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sesions: "admin/sessions"
  }

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, except: [:destroy, :index]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        get 'order'
      end
    end
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  belongs_to :order, optional: true

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy

  has_one_attached :image
  has_many :order_details, dependent: :destroy

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: {
    waiting: 0,
    paid_up: 1,
    making: 2,
    preparing: 3,
    shippend: 4

  }
  has_many :order_details, dependent: :destroy

  def billing_amount
    self.total_price + self.delivery_charge
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order

  belongs_to :item
  enum production_status: {
      untouched: 0,
      waiting: 1,
      working: 2,
      completed: 3
  }
  
  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :get_customer_id, only: [:show, :edit, :update]

  def index
    @customers = Customer.page(params[:page])
  end
  
  def order
    @customer = Customer.find(params[:id])
    @orders = @customer.orders.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
  end

  def edit
  end

  def update
    @original_customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報の編集に成功しました。"
      flash[:color] = "text-success"
      redirect_to admin_customer_path(@customer)
    else
    # エラー箇所に元のデータを代入する
      @original_customer.attributes.each do |attr, value|
        @customer[attr] = value unless @customer.errors[attr].empty?
    end
      flash[:notice] = "会員情報の編集に失敗しました。"
      flash[:color] = "text-danger"
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :email, :is_active)
  end

  def get_customer_id
    @customer = Customer.find(params[:id])
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to request.referer
    else
      @genres = Genre.all
      render index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @items = Item.all.order(created_at: :asc).page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index

    @search = "False"
    @items = Item.page(params[:page]).per(10)

  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :explanation, :price, :image, :genre_id, :is_sell)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_orders_path
    else
        root_path #admins_orders_top_path 遷移先ページが実装されたら変更する
    end
end

def
after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @search = "True"
    @word = params[:word]
    search_items = Item.where("name LIKE?","%#{@word}%")
    @shearch_count = search_items.count
    if admin_signed_in?
      @items = search_items.page(params[:page]).per(10)
      render 'admin/items/index'
    else
      if params[:genre_id]
        genre = Genre.find(params[:genre_id])
        @items = genre.items
      else
        @items = search_items.page(params[:page]).per(8)
      end

      @all_items = search_items.all.page(params[:page]).per(8)
      @genres = Genre.all
      render 'public/items/index'
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container py-5">
  <p class="<%= flash[:color] %>"><%= flash[:notice] %></p>
  <div class="row mt-2 mb-3 offset-1 text-center">
    <h3 class="px-4 title-background"><%= "#{@customer.last_name}#{@customer.first_name}さんの会員情報編集" %></h3>
  </div>

  <div>
    <%= render 'layouts/errors', obj: @customer %>
  </div>

  <%= form_with model: @customer, url: admin_customer_path(@customer), local: true do |f| %>
    <div class="row">
      <div class="col-10 mx-auto">
        <table class="table table-borderless">
          <tr>
            <td class="col-4">会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>

            <td class="col-4"><%= f.label :last_name, "氏名" %></td>

            <td><%= f.text_field :last_name, autofocus: true, class: "form-control" %></td>
            <td><%= f.text_field :first_name, class: "form-control" %></td>
          </tr>
          <tr>

            <td class="col-4"><%= f.label :last_name_kana, "フリガナ" %></td>

            <td><%= f.text_field :last_name_kana, class: "form-control" %></td>
            <td><%= f.text_field :first_name_kana, class: "form-control" %></td>
          </tr>
          <tr>
            <td class="col-4"><%= f.label :postal_code, "郵便番号" %></td>
            <td><%= f.text_field :postal_code, class: "form-control" %></td>
          </tr>
          <tr>
            <td class="col-4"><%= f.label :address, "住所" %></td>
            <td colspan="2"><%= f.text_field :address, :size=> "50", class: "form-control" %></td>
          </tr>
          <tr>
            <td class="col-4"><%= f.label :phone_number, "電話番号" %></td>
            <td><%= f.text_field :phone_number, class: "form-control" %></td>
          </tr>
          <tr>
            <td class="col-4"><%= f.label :email, "メールアドレス" %></td>
            <td><%= f.email_field :email, class: "form-control" %></td>
          </tr>
          <tr>
            <td class="col-4">会員ステータス</td>
            <td>
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active_true, "有効" %>
              <%= f.radio_button :is_active, false, class: "ml-3" %>
              <%= f.label :is_active_false, "退会" %>
            </td>
          </tr>
        </table>
      </div>
    </div>
    <div class="form-group offset-4">
      <%= f.submit "変更を保存", class: "btn btn-success btn-lg" %>
    </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container py-5">
  <p class="<%= flash[:color] %>"><%= flash[:notice] %></p>
  <div class="row mt-2 mb-3 offset-1 text-center">
    <h3 class="px-4 title-background">会員一覧</h3>
  </div>
  <div class="row">
    <div class="col-10 mx-auto">
      <table class="table table-list">
        <thead class="title-background">
          <tr>
            <th>会員ID</th>
            <th><u>氏名</u></th>
            <th>メールアドレス</th>
            <th>ステータス</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><u><%= link_to "#{customer.last_name}#{customer.first_name}", admin_customer_path(customer),  class: "text-reset" %></u></td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.is_active == true %>
                  <p class="text-success">有効</p>
                <% else %>
                  <p class="text-secondary">退会</p>
                <% end %>
              </td>
              <td></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= paginate @customers %>
</div>

app/views/admin/customers/order.html.erb
<div class='container mt-4'>
  <div class='row'>
    <div class="col-12">
      <h3><%= @customer.last_name + @customer.first_name %>さんの注文履歴</h3>
      <table class="table table-bordered border-bottom">
        <thead>
          <tr>
            <th class="table-dark col-3">購入日時</th>
            <th class="table-dark col-3">注文個数</th>
            <th class="table-dark col-3">注文ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td class="table-light">
              <%= link_to admin_order_path(order) do %>
                <%= l order.created_at %>
              <% end %>
            </td>
            <td class="table-light"><%= order.order_details.sum(:amount) %></td>
            <td class="table-light"><%= order.status_i18n %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container py-5">
  <p class="<%= flash[:color] %>"><%= flash[:notice] %></p>
  <div class="row mt-2 mb-3 offset-1 text-center">
    <h3 class="px-4 title-background"><%= "#{@customer.last_name}#{@customer.first_name}さんの会員詳細" %></h3>
  </div>
  <div class="row">
    <div class="col-10 mx-auto">
      <table class="table table-list">
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @customer.last_name %> <%= @customer.first_name %></td>
        </tr>
        <tr>
          <td>カナ</td>
          <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <td>
            <% if @customer.is_active == true %>
              <p class="text-success">有効</p>
            <% else %>
              <p class="text-secondary">退会</p>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-3 offset-2">
      <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %>
    </div>
    <div class="col-3">
      <%= link_to "注文履歴一覧を見る", admin_orders_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>