config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root :to => "homes#top"
    get '/about' => "homes#about"
    resources :items, only: [:index, :show]

    devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
    }

    resource :customers, only: [:show] do
      collection do
        get 'information/edit' => 'customers#edit'
        patch 'information' => 'customers#update'
        get 'check'
        patch 'leave'
      end
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get 'confirm'
        get 'complete'
      end
    end
    resources :addresses, except: [:new, :show]
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sesions: "admin/sessions"
  }

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, except: [:destroy, :index]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        get 'order'
      end
    end
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  belongs_to :order, optional: true

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy

  has_one_attached :image
  has_many :order_details, dependent: :destroy

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: {
    waiting: 0,
    paid_up: 1,
    making: 2,
    preparing: 3,
    shippend: 4

  }
  has_many :order_details, dependent: :destroy

  def billing_amount
    self.total_price + self.delivery_charge
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order

  belongs_to :item
  enum production_status: {
      untouched: 0,
      waiting: 1,
      working: 2,
      completed: 3
  }
  
  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to request.referer
    else
      @genres = Genre.all
      render index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @items = Item.all.order(created_at: :asc).page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index

    @search = "False"
    @items = Item.page(params[:page]).per(10)

  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :explanation, :price, :image, :genre_id, :is_sell)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders = Order.all.order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @product_total = 0
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    if @order.update(order_params)
      @order_details.update_all(production_status: 1) if @order.status == "paid_up"
      redirect_to request.referer
    else
      render :show
    end
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_orders_path
    else
        root_path #admins_orders_top_path 遷移先ページが実装されたら変更する
    end
end

def
after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @search = "True"
    @word = params[:word]
    search_items = Item.where("name LIKE?","%#{@word}%")
    @shearch_count = search_items.count
    if admin_signed_in?
      @items = search_items.page(params[:page]).per(10)
      render 'admin/items/index'
    else
      if params[:genre_id]
        genre = Genre.find(params[:genre_id])
        @items = genre.items
      else
        @items = search_items.page(params[:page]).per(8)
      end

      @all_items = search_items.all.page(params[:page]).per(8)
      @genres = Genre.all
      render 'public/items/index'
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/genres/edit.html.erb
<div class='container mt-4'>
  <div class='row'>
    <div class="col-7">
      <h3 class="ml-5">ジャンル編集</h3>
      <%= form_with model: @genre, url: admin_genre_path do |f| %>
        <div class="field my-5">
          <%= f.label :name, "ジャンル名", class: 'font-weight-bold mr-5' %>
          <%= f.text_field :name, placeholder: "ジャンル名", class: 'mr-5' %>
          <%= f.submit "変更を保存", class: 'btn btn-success font-weight-bold w-25' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class='container mt-4'>
  <div class='row'>
    <div class="col-8">
      <h3 class="ml-5">ジャンル一覧・追加</h3>
      <%= render 'layouts/errors', obj: @genre %>
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
        <div class="field my-5">
          <%= f.label :name, "ジャンル名", class: 'font-weight-bold mr-5' %>
          <%= f.text_field :name, placeholder: "ジャンル名", class: 'mr-5' %>
          <%= f.submit "新規登録", class: 'btn btn-success font-weight-bold w-25' %>
        </div>
      <% end %>
      <div class="col-6">
        <% if @genres.exists? %>
          <table class="table table-bordered border-bottom">
            <thead>
              <tr>
                <th class="table-dark text-center">ジャンル</th>
                <th class="table-dark"></th>
              </tr>
            </thead>
            <tbody>
              <% @genres.each do |genre| %>
                <tr>
                  <td class="table-light"><%= genre.name %></td>
                  <td class="table-light text-center"><%= link_to "編集する", edit_admin_genre_path(genre.id), class: 'btn btn-success' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class='container mt-4'>
  <div class='row'>
    <div class="col-10">
      <h3>商品編集</h3>
      <%= render 'layouts/errors', obj: @item %>
      <div class="col-10 mx-auto">
        <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>
          <div class="fform-group">
            <%= f.label :image, "商品画像", class: 'col-3' %>
            <%= f.file_field :image, accept: 'image/*' %>
          </div>
          <div class="form-group">
            <%= f.label :name, "商品名", class: 'col-3' %>
            <%= f.text_field :name, placeholder: "商品名" %>
          </div>
          <div class="form-group">
            <%= f.label :explanation, "商品説明", class: 'col-3 align-top' %>
            <%= f.text_area :explanation, placeholder: "ここに説明文を記述します", size: "30x5" %>
          </div>
          <div class="form-group">
            <%= f.label :genre_id, "ジャンル", class: 'col-3' %>
            <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
          </div>
          <div class="form-group">
            <%= f.label :price, "税抜価格", class: 'col-3' %>
            <%= f.text_field :price, placeholder: "1000" %>円
          </div>
          <div class="form-group">
            <%= f.label :is_sell, "販売ステータス", class: 'col-3' %>

            <%= f.radio_button :is_sell, true %>
            <%= f.label :is_sell, "販売中", value: true %>

            <%= f.radio_button :is_sell, false %>
            <%= f.label :is_sell, "販売停止中", value: false %>
          </div>
          <div class="form-group">
            <%= f.submit "変更を保存", class: 'btn btn-success font-weight-bold mx-5 w-25' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class='container mt-4'>
  <div class='row'>
    <div class="col-10">
      <h3>商品新規登録</h3>
      <%= render 'layouts/errors', obj: @item %>
      <div class="col-10 mx-auto">
        <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
          <div class="form-group">
            <%= f.label :image, "商品画像", class: 'col-3' %>
            <%= f.file_field :image, accept: 'image/*' %>
          </div>
          <div class="form-group">
            <%= f.label :name, "商品名", class: 'col-3' %>
            <%= f.text_field :name, placeholder: "商品名" %>
          </div>
          <div class="form-group">
            <%= f.label :explanation, "商品説明", class: 'col-3 align-top' %>
            <%= f.text_area :explanation, placeholder: "ここに説明文を記述します", size: "30x5" %>
          </div>
          <div class="form-group">
            <%= f.label :genre_id, "ジャンル", class: 'col-3' %>
            <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), include_blank: "--選択して下さい--" %>
          </div>
          <div class="form-group">
            <%= f.label :price, "税抜価格", class: 'col-3' %>
            <%= f.text_field :price, placeholder: "1000" %>円
          </div>
          <div class="form-group">
            <%= f.label :is_sell, "販売ステータス", class: 'col-3' %>

            <%= f.radio_button :is_sell, true %>
            <%= f.label :is_sell, "販売中" %>

            <%= f.radio_button :is_sell, false %>
            <%= f.label :is_sell, "販売停止中" %>
          </div>
          <div class="form-group">
            <%= f.submit "新規登録", class: 'btn btn-success font-weight-bold mx-5 w-25' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class='container mt-4'>
  <h3 class="m-5">商品詳細</h3>
  <div class='row'>
    <div class="col-md-4 mr-5">
      <%= image_tag @item.get_image(350, 300) %>
    </div>
    <div class="col-md-6">
      <div class="row">
        <p class="col-5">商品名</p>
        <p class="col-7"><%= @item.name %></p>
      </div>
      <div class="row">
        <p class="col-5">商品説明</p>
        <p class="col-7"><%= @item.explanation %></p>
      </div>
      <div class="row">
        <p class="col-5">ジャンル</p>
        <p class="col-7"><%= @item.genre.name %></p>
      </div>
      <div class="row">
        <p class="col-5">
          税込価格<br>
          (税抜価格)
        </p>
        <p class="col-7"><%= @item.with_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</p>
      </div>
      <div class="row">
        <p class="col-5">販売ステータス</p>
        <% if @item.is_sell == true %>
          <p class="col-5 text-success font-weight-bold m-2">販売中</p>
        <% else %>
          <p class="col-5 text-secondary font-weight-bold m-2">販売停止中</p>
        <% end %>
      </div>
      <%= link_to "編集する", edit_admin_item_path(@item), class: 'btn btn-success font-weight-bold w-25 m-5' %>
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class='container mt-4'>
  <div class='row'>
    <div class="col-12">
      <h3>注文履歴一覧</h3>
      <table class="table table-bordered border-bottom">
        <thead>
          <tr>
            <th class="table-dark col-3">購入日時</th>
            <th class="table-dark col-3">購入者</th>
            <th class="table-dark col-3">注文個数</th>
            <th class="table-dark col-3">注文ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td class="table-light">
              <%= link_to admin_order_path(order) do %>
                <%= l order.created_at %>
              <% end %>
            </td>
            <td class="table-light">
              <%= link_to order_admin_customer_path(order.customer) do %>
                <%= order.customer.last_name + order.customer.first_name %>
              <% end %>
            </td>
            <td class="table-light"><%= order.order_details.sum(:amount) %></td>
            <td class="table-light"><%= order.status_i18n %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-12">
      <h3 class="m-5">注文履歴詳細</h3>
      <div class="row">
        <p class="col-3">購入者</p>
        <p class="col-9">
          <%= link_to admin_customer_path(@order.customer) do %>
            <%= @order.customer.last_name + @order.customer.first_name %>
          <% end %>
        </p>
      </div>
      <div class="row">
        <p class="col-3">注文日</p>
        <p class="col-9"><%= l @order.created_at, format: :short %></p>
      </div>
      <div class="row">
        <p class="col-3">配送先</p>
        <p class="col-9">
          〒<%= @order.postal_code.to_s.insert(3, "-") %><%= @order.address %><br>
          <%= @order.name %>
        </p>
      </div>
      <div class="row">
        <p class="col-3">支払方法</p>
        <p class="col-9"><%= @order.payment_method_i18n %></p>
      </div>
      <div class="row">
        <p class="col-3">注文ステータス</p>
          <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
            <%= f.select :status, Order.statuses_i18n.invert %>
            <%= f.submit "更新", class: 'btn btn-success' %>
          <% end %>
      </div>
      <div class="row">
        <div class="col-9">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th class="table-dark">商品名</th>
                <th class="table-dark">単価(税込)</th>
                <th class="table-dark">数量</th>
                <th class="table-dark">小計</th>
                <th class="table-dark">製作ステータス</th>
              </tr>
            </thead>
            <tbody>
              <% @order_details.each do |order_detail| %>
                <tr>

                  <td class="table-light"><%= order_detail.item.name %></td>
                  <td class="table-light"><%= order_detail.purchase_price.to_s(:delimited) %></td>
                  <td class="table-light"><%= order_detail.amount %></td>
                  <td class="table-light"><%= (order_detail.purchase_price * order_detail.amount).to_s(:delimited) %></td>
                      <% @product_total += order_detail.subtotal %> 
=
                  <%= form_with model: order_detail, url: admin_order_order_detail_path(@order, order_detail), method: :patch do |f| %>
                  <td class="table-light">
                    <%= f.select :production_status, OrderDetail.production_statuses_i18n.invert %>
                    <%= f.submit "更新", class: 'btn btn-success' %>
                  </td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <table>
          <tr>
            <th>商品合計</th>
            <td><%= @product_total.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td><%= @order.delivery_charge %>円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td><%= @order.total_price.to_s(:delimited) %>円</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>