config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root :to => "homes#top"
    get '/about' => "homes#about"
    resources :items, only: [:index, :show]

    devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
    }

    resource :customers, only: [:show] do
      collection do
        get 'information/edit' => 'customers#edit'
        patch 'information' => 'customers#update'
        get 'check'
        patch 'leave'
      end
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get 'confirm'
        get 'complete'
      end
    end
    resources :addresses, except: [:new, :show]
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sesions: "admin/sessions"
  }

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, except: [:destroy, :index]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        get 'order'
      end
    end
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  belongs_to :order, optional: true

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy

  has_one_attached :image
  has_many :order_details, dependent: :destroy

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: {
    waiting: 0,
    paid_up: 1,
    making: 2,
    preparing: 3,
    shippend: 4

  }
  has_many :order_details, dependent: :destroy

  def billing_amount
    self.total_price + self.delivery_charge
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order

  belongs_to :item
  enum production_status: {
      untouched: 0,
      waiting: 1,
      working: 2,
      completed: 3
  }
  
  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @items = Item.all.order(created_at: :asc).page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index

    @search = "False"
    @items = Item.page(params[:page]).per(10)

  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :explanation, :price, :image, :genre_id, :is_sell)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_orders_path
    else
        root_path #admins_orders_top_path 遷移先ページが実装されたら変更する
    end
end

def
after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @search = "True"
    @word = params[:word]
    search_items = Item.where("name LIKE?","%#{@word}%")
    @shearch_count = search_items.count
    if admin_signed_in?
      @items = search_items.page(params[:page]).per(10)
      render 'admin/items/index'
    else
      if params[:genre_id]
        genre = Genre.find(params[:genre_id])
        @items = genre.items
      else
        @items = search_items.page(params[:page]).per(8)
      end

      @all_items = search_items.all.page(params[:page]).per(8)
      @genres = Genre.all
      render 'public/items/index'
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %>

<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h5><%= obj.errors.count %>件のエラーが発生しました</h5>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container-fulid border-top">
  <div class="row">
    <div style="height: 100px;">
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="container-fulid">
  <div class="row mx-auto" style="background-image:url(<%= asset_path "pattern.svg", :size => '30x20' %>);　no-repeat center top; background-size:100%;background-color: #ffbe3ac7">
    <div class="col-3">
      <div class="logo pt-2">
        <%= link_to root_path do %>
          <%= image_tag 'nagano-cake-logo.png', :size => '100x100' %>
        <% end %>
      </div>
    </div>
    <div class="col-3 mt-4 text-right text-light">

      <% if customer_signed_in?%>
      <div class="customer_name mt-3">
        <span class="text-dark"><%= "ようこそ、#{current_customer.last_name}さん！" %></span>
      </div>
      <% end %>
    </div>
    <div class="col-6">
      <div class="row justify-content-end my-2">
        <% if admin_signed_in? %>
        
          <div class="mr-3 menu"><%= link_to '商品一覧', admin_path, class: "btn btn-light" %></div>
          <div class="mr-3 menu"><%= link_to '会員一覧', admin_customers_path, class: "btn btn-light" %></div>
          <div class="mr-3 menu"><%= link_to '注文履歴一覧', admin_orders_path, class: "btn btn-light" %></div>
          <div class="mr-3 menu"><%= link_to 'ジャンル一覧', admin_genres_path, class: "btn btn-light" %></div>
          <div class="mr-3 menu"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "btn btn-light" %></div>


        <% elsif customer_signed_in? %>
          <div class="mr-3 menu"><%= link_to 'マイページ', customers_path, class: "btn btn-light" %></div>
          <div class="mr-3 menu"><%= link_to '商品一覧', items_path, class: "btn btn-light" %></div>
          <div class="mr-3 menu"><%= link_to 'カート', cart_items_path, class: "btn btn-light" %></div>
          <div class="mr-3 menu"><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: "btn btn-light" %></div>
        <% else %>
          <div class="mr-3 menu"><%= link_to 'About', about_path, class: "btn btn-light" %></div>
          <div class="mr-3 menu"><%= link_to '商品一覧', items_path, class: "btn btn-light" %></div>
          <div class="mr-3 menu"><%= link_to '新規登録', new_customer_registration_path, class: "btn btn-light" %></div>
          <div class="mr-3 menu"><%= link_to 'ログイン', customer_session_path, class: "btn btn-light" %></div>
        <% end %>
      </div>
      <div class="row justify-content-end mt-3 mb-2 mr-1">
        <%# if admin_signed_in? %>
          <%#= render 'admin/searches/search' %>
        <%# else %>
          <%#= render 'public/searches/search' %>
        <%# end %>
        <%= render 'layouts/search' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_search.html.erb
<%= form_with url: search_path, class: "search_form w-50", method: :get do |f| %>
  <%= f.text_field :word, class: "w-100", placeholder: "Search",autocomplete: "off" ,value: @word %>
  <%= image_submit_tag("search25.jpg", class: 'search_image', name: "search") %>
  <%#= button_tag type: "submit", value: "search", class: "btn btn-default" do %>
  <%#= image_tag "search.jpg", size: "25x25", class: "search_image" %>
  <%# end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/25efbb1178.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <header class="bar-color">
        <%= render 'layouts/header' %>
      </header>
      <main class="main-background" style="background-image:url(<%= asset_path "pattern.svg", :size => '30x20' %>);　no-repeat center top; background-size:100%;background-color: #e69a9a52">
        <%= yield %>
      </main>
      <footer class="bar-color" style="background-image:url(<%= asset_path "pattern.svg", :size => '30x20' %>);　no-repeat center top; background-size:100%;background-color:#db000052">
        <%= render 'layouts/footer' %>
      </footer>
    </div>
  </body>
</html>